import * as monaco from 'monaco-editor';

export const COMPARE_THEME_ID = 'compare-dark';

export const COMPARE_THEME = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'E6EDF3' },
    { token: 'source', foreground: 'E6EDF3' },
    { token: 'comment', foreground: 'B1BAC4' },
    { token: 'comment.*', foreground: 'B1BAC4' },
    { token: 'keyword', foreground: 'D2A8FF' },
    { token: 'keyword.*', foreground: 'D2A8FF' },
    { token: 'storage', foreground: 'D2A8FF' },
    { token: 'control', foreground: 'D2A8FF' },
    { token: 'string', foreground: 'A5D6FF' },
    { token: 'string.*', foreground: 'A5D6FF' },
    { token: 'number', foreground: 'F2CC60' },
    { token: 'number.*', foreground: 'F2CC60' },
    { token: 'constant.numeric', foreground: 'F2CC60' },
    { token: 'constant.language', foreground: 'F2CC60' },
    { token: 'constant.character', foreground: 'F2CC60' },
    { token: 'type', foreground: '79C0FF' },
    { token: 'type.*', foreground: '79C0FF' },
    { token: 'type.identifier', foreground: '79C0FF' },
    { token: 'class', foreground: '79C0FF' },
    { token: 'interface', foreground: '79C0FF' },
    { token: 'namespace', foreground: '79C0FF' },
    { token: 'function', foreground: 'E6EDF3' },
    { token: 'function.*', foreground: 'E6EDF3' },
    { token: 'method', foreground: 'E6EDF3' },
    { token: 'identifier', foreground: 'E6EDF3' },
    { token: 'variable', foreground: 'E6EDF3' },
    { token: 'property', foreground: 'E6EDF3' },
    { token: 'operator', foreground: 'B1BAC4' },
    { token: 'delimiter', foreground: 'B1BAC4' },
    { token: 'delimiter.*', foreground: 'B1BAC4' },
    { token: 'punctuation', foreground: 'B1BAC4' },
    { token: 'tag', foreground: 'D2A8FF' },
    { token: 'attribute.name', foreground: 'A5D6FF' },
    { token: 'invalid', foreground: 'FFA198', fontStyle: 'underline' },
    { token: 'invalid.*', foreground: 'FFA198', fontStyle: 'underline' },
  ],
  colors: {
    'editor.background': '#0D1117',
    'editor.foreground': '#E6EDF3',
    'editorGutter.background': '#010409',
    'editorLineNumber.foreground': '#8B949E',
    'editorLineNumber.activeForeground': '#E6EDF3',
    'editorCursor.foreground': '#58A6FF',
    'editorWhitespace.foreground': '#484F5880',
    'editorIndentGuide.background1': '#21262D',
    'editorIndentGuide.activeBackground1': '#30363D',
    'editor.selectionBackground': '#388BFD59',
    'editor.inactiveSelectionBackground': '#388BFD40',
    'editor.selectionForeground': '#FFFFFF',
    'editor.lineHighlightBackground': '#00000000',
    'editor.lineHighlightBorder': '#484F58',
    'editorOverviewRuler.border': '#30363D',
    'diffEditor.insertedLineBackground': '#2EA04338',
    'diffEditor.removedLineBackground': '#F8514938',
    'diffEditor.insertedTextBackground': '#2EA04373',
    'diffEditor.removedTextBackground': '#F8514973',
    'diffEditorGutter.insertedLineBackground': '#2EA04338',
    'diffEditorGutter.removedLineBackground': '#F8514938',
    'diffEditorOverview.insertedForeground': '#3FB950',
    'diffEditorOverview.removedForeground': '#F85149',
    'diffEditor.border': '#30363D',
    'diffEditor.diagonalFill': '#010409',
    'diffEditor.unchangedCodeBackground': '#0D1117',
    'diffEditor.unchangedRegionBackground': '#161B22',
    'diffEditor.unchangedRegionForeground': '#A371F7',
    'diffEditor.unchangedRegionShadow': '#00000000',
    'editorWidget.background': '#21262D',
    'editorWidget.foreground': '#E6EDF3',
    'editorWidget.border': '#30363D',
    'editorHoverWidget.background': '#21262D',
    'editorHoverWidget.foreground': '#E6EDF3',
    'editorHoverWidget.border': '#30363D',
    focusBorder: '#58A6FF',
    'scrollbarSlider.background': '#30363D80',
    'scrollbarSlider.hoverBackground': '#484F58A6',
    'scrollbarSlider.activeBackground': '#484F58',
  },
} satisfies monaco.editor.IStandaloneThemeData;

export function applyCompareTheme(): void {
  monaco.editor.defineTheme(COMPARE_THEME_ID, COMPARE_THEME);
  monaco.editor.setTheme(COMPARE_THEME_ID);
}
